services:
  postgres:
    image: 'postgres'
    container_name: 'if-ride-postgres'
    environment:
      POSTGRES_DB: 'if-ride-core'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: